icinga_status_list:
  path: /icinga/status
  methods: [GET]
  defaults:
    _controller: RavuAlHemioIcingaStatusBundle:StatusList:statusList

icinga_service_matrix:
  path: /icinga/matrix
  methods: [GET]
  defaults:
    _controller: RavuAlHemioIcingaStatusBundle:ServiceMatrix:serviceMatrix
